spring:
  devtools:
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:postgresql://118.67.135.211:5432/kiosk
    username: kiosk
    password: zpshrzzang
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

openai-service:
  api-key: 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
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions


springdoc:
  swagger-ui:

    base-url: /swagger-ui/index.html
    disable-swagger-default-url: true

    # path: /api
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/swagger.json
    groups:
      enabled: true
  cache:
    disabled: true

