spring:
  devtools:
    restart:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false

openai-service:
  api-key: ${OPENAI_API_KEY}
  gpt-model: gpt-3.5-turbo
  audio-model: whisper-1
  http-client:
    read-timeout: 3000
    connect-timeout: 3000
  urls:
    base-url: https://api.openai.com/v1
    chat-url: /chat/completions
    create-transcription-url: /audio/transcriptions


springdoc:
  swagger-ui:

    base-url: /swagger-ui/index.html
    disable-swagger-default-url: true

    # path: /api
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api/swagger.json
    groups:
      enabled: true
  cache:
    disabled: true
chatbot:
  api:
    url: ${CHATBOT_API_URL}
    key: ${CHATBOT_API_KEY}
secret:
  key: ${SECRET_KEY}
